import Footer from "@/components/layout/footer/footer";
import Header from "@/components/layout/header/header";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function MainLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
				<div className="flex flex-col min-h-screen">
					<Header />
					<main className="flex-grow-1 relative">{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	);
}
