import "@/app/globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout: React.FC<{
	children: React.ReactNode;
}> = ({ children }) => {
	return (
		<html>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
				{children}
			</body>
		</html>
	);
};

export default RootLayout;
