import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Footer from "@/components/layout/footer/footer";
import Header from "@/components/layout/header/header";
import AuthProvider from "@/libs/redux/providers/AuthProvider";
import StoreProvider from "@/libs/redux/providers/storeProvider";

import "@/app/globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const MainLayout: React.FC<{
	children: React.ReactNode;
}> = ({ children }) => {
	return (
		<html>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
				<StoreProvider>
					<AuthProvider>
						<div className="flex flex-col min-h-screen">
							<Header />
							<main className="flex-grow-1 flex relative mt-15 w-full">{children}</main>
							<Footer />
						</div>
					</AuthProvider>
				</StoreProvider>
			</body>
		</html>
	);
};

export default MainLayout;
